version: '3.3'
services:
    altstore-proxy:
        container_name: 'AltStore-Proxy'
        ports:
            - 'port:8080'
        volumes:
            - '/path/to/cache/:/cache:rw'
        environment:
            - 'BASEURL=https://example.com'
            - 'REPOS=https://fake.tld/apps.json,https://foo.bar/altstore.json'
            - 'DISCORD_WEBHOOK=https://discord.com/api/webhooks/foo/bar'
        image: 'rix1337/docker-altstore-proxy:latest'
